on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  issue_comment:
    types: [created]

jobs:
  pr_agent:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: write
    name: 🧠 Qodo Merge PR‑Agent
    steps:
      - name: Run pr-agent
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          GOOGLE_AI_STUDIO.GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG__MODEL: "gemini/gemini-2.5-pro"
          CONFIG__FALLBACK_MODELS: '["gemini/gemini-2.5-pro"]'
          github_action.auto_review: "true"
          github_action.auto_describe: "true"
          github_action.auto_improve: "true"
          pr_update_changelog.push_changelog_changes: "true"
